version: '3.9'

services:

  db:  #サービス名
    image: postgres:latest  #ビルドに使用するimageファイル
    container_name: huyou-postgres  #コンテナの名前
    environment:
      POSTGRES_DB: 'huyou'  #データベース名
      POSTGRES_PASSWORD: 'huyouhuyou'  #データベースパスワード
      POSTGRES_USER: 'postgres'  #データベースユーザ名
      TimeZone: Asia/Tokyo  #タイムゾーン
    ports:
      - '5432:5432'
    volumes:  #マウントディレクトリ
      - /var/lib/postgres/data

volumes:
  go-data:
