version: '3.9'

services:

  db:  #サービス名
    image: postgres:latest  #ビルドに使用するimageファイル
    container_name: huyou-postgres  #コンテナの名前
    environment:
      POSTGRES_DB: 'huyou'  #データベース名
      POSTGRES_PASSWORD: 'huyouhuyou'  #データベースパスワード
      POSTGRES_USER: 'postgres'  #データベースユーザ名
      TimeZone: Asia/Tokyo  #タイムゾーン
    ports:
      - '5432:5432'
    volumes:  #マウントディレクトリ
      - /var/lib/postgres/data
  
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8080:8081"
    environment:
      DATABASE_URL: postgres://postgres:huyouhuyou@db:5432/postgres?sslmode=disable
    depends_on:
      - db


volumes:
  go-data:
