package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"
	"math/rand"

	"github.com/ryuji-cre8ive/huyou-server/graph/model"
)

// CreateShopItem is the resolver for the createShopItem field.
func (r *mutationResolver) CreateShopItem(ctx context.Context, input model.NewShopItem) (*model.ShopItem, error) {
	shopItem := &model.ShopItem{
		Title:  input.Title,
		ID:     fmt.Sprintf("T%d", rand.Int()),
		Seller: &model.User{ID: input.ID, Name: "user " + input.ID},
	}
	r.shopItems = append(r.shopItems, shopItem)
	return shopItem, nil
}

// Items is the resolver for the items field.
func (r *queryResolver) Items(ctx context.Context) ([]*model.ShopItem, error) {
	panic(fmt.Errorf("not implemented: Items - items"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }